import { createSlice } from '@reduxjs/toolkit';

export const slice = createSlice({
  name: 'skills',
    initialState: {
        skills: {
                '10000': {id: '10000', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10001': {id: '10001', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10002': {id: '10002', isShow: false, activeIcon: '', disabledIcon: '', active: '', hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10003': {id: '10003', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10004': {id: '10004', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10005': {id: '10005', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10006': {id: '10006', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10007': {id: '10007', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10008': {id: '10008', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10009': {id: '10009', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10010': {id: '10010', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10011': {id: '10011', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10012': {id: '10012', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10013': {id: '10013', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10014': {id: '10014', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10015': {id: '10015', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10016': {id: '10016', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10017': {id: '10017', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10018': {id: '10018', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10019': {id: '10019', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10020': {id: '10020', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10021': {id: '10021', isShow: false, activeIcon: '', disabledIcon: '', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10022': {id: '10022', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10023': {id: '10023', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10024': {id: '10024', isShow: false, activeIcon: '', disabledIcon: '', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10025': {id: '10025', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10026': {id: '10026', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10027': {id: '10027', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10028': {id: '10028', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10029': {id: '10029', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10030': {id: '10030', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10031': {id: '10031', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10032': {id: '10032', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10033': {id: '10033', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10034': {id: '10034', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10035': {id: '10035', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '10036': {id: '10036', isShow: false, activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
            
        }
    },
    reducers: {
        setfullTable: (state, action) => {
            state.skills = action.payload
        },
        setRow: (state, action) => {
            state.skills[action.payload.id] = action.payload
        }
    },
});


export const { setfullTable, setRow } = slice.actions;

export const selectTable = state => state.skills.skills;

export default slice.reducer;
