import { createSlice } from '@reduxjs/toolkit';

export const slice = createSlice({
  name: 'skills',
    initialState: {
        skills: {
                '0': {id: '10000', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '1': {id: '10001', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '2': {},
                '3': {id: '10003', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '4': {},
                '5': { id: '10005', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '6': {id: '10006', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '7': {},
                '8': {id: '10008', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '9': {},
                '10': {},
                '11': {},
                '12': {},
                '13': {},
                '14': {},
                '15': {id: '10015', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '16': {id: '10016', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '17': {id: '10017', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '18': {id: '10018', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '19': {},
                '20': {},
                '21': {},
                '22': {id: '10022', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '23': {id: '10023', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '24': {},
                '25': {id: '10025', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '26': {id: '10026', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '27': {id: '10027', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '28': {id: '10028', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '29': {id: '10029', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '30': {id: '10030', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '31': {id: '10031', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '32': {id: '10032', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '33': {id: '10033', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '34': {id: '10034', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '35': {id: '10035', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: false, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
                '36': {id: '10036', category:'Дизайн', sliderIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Circle-icons-camera.svg/1200px-Circle-icons-camera.svg.png', activeIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2048px-Circle-icons-gamecontroller.svg.png', disabledIcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Circle-icons-money.svg/768px-Circle-icons-money.svg.png', active: true, hoverText: 'Подавление агрессии в коолективе', complitedLesson: '4', fullLesson: '20'},
        },
    },
    reducers: {
        setfullTable: (state, action) => {
            state.skills = action.payload
        },
        setRow: (state, action) => {
            state.skills[action.payload[0]] = action.payload[1]
        }
    },
});


export const { setfullTable, setRow } = slice.actions;

export const selectTable = state => state.skills.skills;

export default slice.reducer;
